### ISSUE TITLE
[Bug] Blender 2.79b - Collision import error. AttributeError: 'Object' object has no attribute 'empty_display_type'

### ISSUE THREAD

**Issue by RenanMsV** [Zarig/DragonFF#6]
Im using Blender 2.79b.
Im using Plugin #v0.0.1 release.

```python
faces.new(verts): face already exists
Traceback (most recent call last):
  File "C:\Users\Renan\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\a
ddons\gta_by_dragonFF\gui.py", line 252, in execute
    'use_mat_split': self.read_mat_split
  File "C:\Users\Renan\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\a
ddons\gta_by_dragonFF\dff_importer.py", line 509, in import_dff
    dff_importer.import_dff(options['file_name'])
  File "C:\Users\Renan\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\a
ddons\gta_by_dragonFF\dff_importer.py", line 495, in import_dff
    col = import_col_mem(collision, os.path.basename(file_name), False)
  File "C:\Users\Renan\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\a
ddons\gta_by_dragonFF\col_importer.py", line 167, in import_col_mem
    return col.add_to_scene(collection_prefix, link)
  File "C:\Users\Renan\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\a
ddons\gta_by_dragonFF\col_importer.py", line 132, in add_to_scene
    self.__add_spheres(collection, model.spheres)
  File "C:\Users\Renan\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\a
ddons\gta_by_dragonFF\col_importer.py", line 58, in __add_spheres
    obj.empty_display_type = 'SPHERE'
AttributeError: 'Object' object has no attribute 'empty_display_type'

location: <unknown location>:-1

location: <unknown location>:-1

```

- [x] It is Importing the model + model_vlo.
- [ ] But not importing the collision mesh.

**Comment by Zarig** [comment]
Hey,

I have fixed the issue in the most recent build. Could you please confirm that it fixed the model on your end?

Also, I plan to make some changes to the way the collision models import to make them easier to work with in 2.79. Also, as of now, the export function for Collision Meshes is not complete, however, the collision is provided at the moment just to have a look at how the collision file looks. The collision model imported from a San Andreas Vehicle Model is exported as is, even if you make changes to the model.

P.S I believe you meant 2.79 and not 0.79 :wink:

**Comment by RenanMsV** [comment]
You're great!
You did fix it so fast!
It is now importing the collision mesh.

And yes my mistake, its 2.79 not 0.79
